- README.md
- android/build.gradle
- build.sh
- jvm/build.gradle
* Use latest version of `bdk-ffi`
* Update README and build.sh to build JVM bdk-ffi libs for macos intel (x86-64) and m1 (aarch64).
* Change version to 0.3.0
> Build JVM bdk-ffi libs for macos m1

- README.md
This step exists in bdk-ffi readme, but is missing in this repo, and build.sh fails without it.
> Add step to install uniffi-bindgen on README

- android/src/androidTest/kotlin/org/bitcoindevkit/AndroidLibTest.kt
- jvm/src/test/kotlin/org/bitcoindevkit/JvmLibTest.kt
Update `bdk-ffi` version to `v0.3.0`, fix corresponding test code and add tests for new `PartiallySignedBitcoinTransaction` deserialize and serialize methods. Fixes #12.
As part of the upgrade to `bdk-ffi` `v0.3.0` we also:
1. Removed the `OfflineWallet` and renamed `OnlineWallet` to `Wallet`
2. Added a change descriptor to the `Wallet` constructor
> Update `bdk-ffi` version to `v0.3.0`, test `PartiallySignedBitcoinTransaction` serialization

- README.md
- build.gradle.kts
This removes the compiler option to use experimental unsigned types, since they are not experimental anymore as of Kotlin 1.5. I have added a line in our readme specifying our use of Kotlin 1.6.10 or above for compilation of the library.
> Remove compiler option for experimental unsigned types

- README.md
- android/src/androidTest/kotlin/org/bitcoindevkit/AndroidLibTest.kt
- jvm/src/test/kotlin/org/bitcoindevkit/JvmLibTest.kt
Add sqlite database option. 
https://github.com/bitcoindevkit/bdk-ffi/pull/116 needs to be merged first.
Using the sqlite database should also fix https://github.com/bitcoindevkit/bdk-ffi/issues/114.
> Add sqlite database option

- README.md
This PR adds a few lines documenting how to skip the `signMavenPublication` task when publishing to Maven local.
Fixes #21
> Add documentation on how to skip signing task for local Maven

- README.md
- android/build.gradle.kts
- jvm/build.gradle.kts
Fix publish by building javadocs for jvm on build.
Also incrementing master branch version to `0.6.0-SNAPSHOT`. Also changed README to not have a hardcoded version.
> Add javadocs to jvm build

- android/src/androidTest/kotlin/org/bitcoindevkit/AndroidLibTest.kt
Fixes the Android tests that used the memory database config with the new API.
> Fix database memory test

- README.md
- build.sh
`ANDROID_HOME`, `ANDROID_SDK_HOME`, and `ANDROID_NDK_HOME` are not used by the Android platform and SDK tools so these are considered deprecated/invalid.
Google recommends using `ANDROID_SDK_ROOT` and `ANDROID_NDK_ROOT` instead:
- https://groups.google.com/g/android-ndk/c/qZjhOaynHXc/m/2ux2ZZdxy2MJ
- https://developer.android.com/studio/command-line/variables
> Update README and build.sh script to use latest env var naming.

- .github/workflows/test.yaml
Added CI test steps to install and build the bdk-ffi libs that the kotlin tests depend on. 
I also added caching, but it's still a bit slow. It's something to try and fix in a future PR. Another thing to do in the future is to start up an android emulator and run the android tests.
> Add CI steps to build bdk-ffi libraries

- android/build.gradle.kts
- build.gradle.kts
Currently sources and javadocs are not being published for bdk-android artifact (unlike bdk-jvm) which makes it impossible to look up sources and documentation of bdk-android in IDE when using it in any project. AGP 7.1.0 added new APIs to `maven-publish` plugin to allow publishing sources and javadocs for Android super easy, which are being used here.
> #32: Enable publishing bdk-android sources and java docs

- android/build.gradle.kts
- jvm/build.gradle.kts
This PR adds the version of the library to the Dokka docs. The final website looks like this:
<br>
This PR fixes #42.
> Add library version to API docs

- .github/workflows/test.yaml
- android/src/androidTest/kotlin/org/bitcoindevkit/AndroidLibTest.kt
- docs.patch
- jvm/src/test/kotlin/org/bitcoindevkit/JvmLibTest.kt
Update bdk-ffi to https://github.com/bitcoindevkit/bdk-ffi/pull/123 and add new TxBuilder tests.
I also fixed tests to use network and addresses for TESTNET to match BlockchainConfig. 
The tests must be a bit hacky until we have a way to use REGTEST for our Kotlin tests.
> Update bdk-ffi to 0.5 (with TxBuilder APIs)

- android/build.gradle.kts
- build.gradle.kts
- jvm/build.gradle.kts
This PR fixes a regression introduced with the upgrade to Android Gradle Plugin `7.1.2`, where the Dokka theme applied to the API docs is an older version. I opened an issue on this and they were kind enough to look into it and provide a solution. See kotlin/dokka#2415
This is the fix recommended by the Dokka team, which is to apply the Dokka plugin at the root of the project.
> Fix dokka theme bug with AGP

- android/src/androidTest/kotlin/org/bitcoindevkit/AndroidLibTest.kt
- docs.patch
- jvm/src/test/kotlin/org/bitcoindevkit/JvmLibTest.kt
Major API changes from bdk-ffi 0.5.0 -> 0.6.0:
* new `Blockchain` class constructed from `BlockchainConfig`
* `Wallet` sync method requires a `Blockchain` and optional `Progress` callback
* `Blockchain` broadcast method returns no txid value
* new `PartiallySignedBitcoinTransaction` method to get txid
* `TxBuilder.build` renamed to `TxBuilder.finish` to match rust `bdk` API
> Update to bdk-ffi 0.6.0 (remove Blockchain from Wallet)

- buildSrc/src/main/kotlin/org/bitcoindevkit/plugins/Enums.kt
- buildSrc/src/main/kotlin/org/bitcoindevkit/plugins/generate-jvm-bindings.gradle.kts
This PR changes the Gradle plugin to ensure both `x86_64` and `aarch64` versions of `bdk-jvm` get built whenever one calls the `buildJvmLib` command from macOS.
This PR is still in draft mode because I need to test that the cross-compilation from an x86_64 mac works. In theory it should (it's one of the targets for the Rust compiler), but I have not tried it for myself yet.
> Build both x86_64 and aarch64 binaries when building bdk-jvm on macOS

- .github/workflows/test.yaml
- android/build.gradle.kts
- android/src/androidTest/kotlin/org/bitcoindevkit/AndroidLibTest.kt
- jvm/src/test/kotlin/org/bitcoindevkit/JvmLibTest.kt
This PR is the migration to bdk-ffi `0.7.0`, and updates to the test suite.
Both test suites have been upgraded.
> Bump bdk-ffi submodule to 0.7.0 and update tests

- .gitmodules
Feat #59. Minor change to the `.gitmodule` folder url to use `HTTPS` instead of `SSH` to avoid SSH key authentication from Github.
Users might have to call `git submodule sync --recursive` to sync the `.gitmodule` folder.
> feat: updated gitmodule to use HTTPS

- .github/workflows/test.yaml
The CI was installing uniffi-bindgen, but that's not necessary now that we have the crate to do it internally.
> Remove install of uniffi-bindgen in CI workflow

- .github/workflows/test.yaml
This PR fixes our test CI workflow. The workflow stopped working on August 1st [when GitHub deprecated the Android NDK v21 in the Ubuntu CI images](https://github.com/actions/runner-images/issues/5930).
This PR uses GitHub's proposed fix for installing the old NDK at runtime (see link above) because when I tried to simply migrate to the more recent v25 version we ran into compatibility issues with the Rust compilation steps. I think in the long run we should look into how we can migrate the NDK but for now this will work. I also pinned the version of Ubuntu the CI uses (`ubuntu-20.04`) instead of leaving it at `ubuntu-latest` (they're currently the same version but pinning it makes this versioning more explicit).
Note that we'll need to merge this before #72 and #76.
> Fix CI test workflow by using Android NDK 21

- .github/workflows/publish-jvm.yaml
- .github/workflows/test-android.yaml
- .github/workflows/test-jvm.yaml
This is the first draft at a workflow that will publish bdk-jvm and bdk-android to Maven Central
The workflow currently gets triggered manually and only offer the artifact that is published to MavenLocal for download. To trigger the workflow, go to `Actions -> Publish bdk-jvm to Maven Central -> Trigger workflow`
Not ready for real publishing yet, but we need to merge something small first if we want to test and manually trigger the runs.
> Add workflow to publish bdk-jvm

- .github/workflows/publish-jvm.yaml
- build.gradle.kts
- jvm/build.gradle.kts
This allows us to sign the releases on the CI. One step further on the way to full publishing using the CI.
This uses GitHub secrets, which I have confirmed do not get printed to logs.
> Sign bdk-jvm artifact in CI

- .github/workflows/publish-android.yaml
- .github/workflows/publish-jvm.yaml
- android/build.gradle.kts
- build.gradle.kts
- jvm/build.gradle.kts
This PR adds the ability to sign artifacts in the CI workflows, and adds a minor cleanup that removes unused Dokka blocks and imports.
The artifacts come out properly signed with key
```
88AD93AC4589FD090FF3B8D12768C43E8803C6A3
bitcoindevkit-bindings <bindings@bitcoindevkit.org>
```
You can see the test run [here](https://github.com/bitcoindevkit/bdk-kotlin/actions/runs/2966179914).
I think we might want to upload the PGP public key in ascii-armor format to the root of this repo? @notmandatory let me know what you think.
> Sign artifacts in CI and publish to Maven Central staging repository

- .github/workflows/publish-android.yaml
- .github/workflows/publish-jvm.yaml
This adds the ability for the CI to pull from GitHub secrets and use the credentials for Maven Central publishing.
> Pick up Nexus credentials from GitHub secrets

- jvm/build.gradle.kts
The error we're getting in the CI publishing workflow is the following:
```shell
> Task :initializeSonatypeStagingRepository
Created staging repository 'orgbitcoindevkit-1110' at https://s01.oss.sonatype.org/service/local/repositories/orgbitcoindevkit-1110/content/
FAILURE: Build failed with an exception.
* What went wrong:
> Task :jvm:publishMavenPublicationToSonatypeRepository FAILED
Execution failed for task ':jvm:publishMavenPublicationToSonatypeRepository'.
> Failed to publish publication 'maven' to repository 'sonatype'
17 actionable tasks: 12 executed, 5 up-to-date
> Could not PUT 'https://s01.oss.sonatype.org/service/local/staging/deployByRepositoryId/orgbitcoindevkit-1110/org/bitcoindevkit/bdk-jvm/0.9.0-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Bad …
```
> Remove SNAPSHOT from artifact version

- .github/workflows/publish-android.yaml
- .github/workflows/publish-jvm.yaml
- android/Module.md
- android/build.gradle.kts
- build.gradle.kts
- jvm/Module.md
- jvm/build.gradle.kts
This PR brings in the ability for the CI to publish the bdk-jvm and bdk-android libraries on the Maven Central _staging repository_. Once there we could publish them manually in the UI, or simply merge a further PR that will enable full publishing.
Notes:
1. These workflows can currently only be triggered manually by doing
```
Actions -> <workflow> -> Run workflow -> <branch>
```
2. These workflows will _only_ work with full release versions, i.e. you cannot trigger them with a SNAPSHOT version name (the Nexus repository will reject them).
> Publish bdk-jvm and bdk-android on Maven Central

- android/build.gradle.kts
- jvm/build.gradle.kts
This PR bumps the snapshot version on master from `0.9.0-SNAPSHOT` to `0.10.0-SNAPSHOT`.
> Bump SNAPSHOT version to 0.10.0-SNAPSHOT

- api-docs/Module.md
- api-docs/Module1.md
- api-docs/Module2.md
- api-docs/build.gradle.kts
- api-docs/src/main/kotlin/org/bitcoindevkit/bdk.kt
This PR adds a commented out section in the build script for the docs that can build the API docs website into its "bdk-jvm" counterpart.
The site content is identical to bdk-android but for the header and the home page.
The way to build both websites it simply to comment out one or the other parts and call the `./gradlew dokkaHtml` task.
> Add option to build API docs into bdk-jvm website

- .github/workflows/publish-android.yaml
- .github/workflows/publish-jvm.yaml
- bdk-android/build.gradle.kts
- bdk-android/lib/build.gradle.kts
- bdk-jvm/build.gradle.kts
- bdk-jvm/lib/build.gradle.kts
This PR is a cherry-pick of 6c904cd26e6d994ab7e529856f580541d97a7a89 and 579c7cb07e2dc61a229d5f34ff775d680299d49b that adds the `group` and `version` properties to the root `build.gradle.kts` file. These properties are required for the nexus publish-plugin to work properly.
It also makes the default publishing workflow publish entirely instead of only to the staging repo.
Related to this PR is issue #101.
> Add group and version properties for nexus publishing plugin

- bdk-android/build.gradle.kts
- bdk-android/lib/build.gradle.kts
- bdk-jvm/build.gradle.kts
- bdk-jvm/lib/build.gradle.kts
This PR bumps the snapshot versions to `0.11.0-SNAPSHOT`.
> Bump versions to 0.11.0-SNAPSHOT

- bdk-android/plugins/src/main/kotlin/org/bitcoindevkit/plugins/UniFfiAndroidPlugin.kt
- bdk-jvm/plugins/src/main/kotlin/org/bitcoindevkit/plugins/UniFfiJvmPlugin.kt
This PR bumps the submodule to the latest version, `v0.11.0`.
> Bump bdk-ffi submodule to v0.11.0
